name: lfudacaching
version: 0.1.0
github: "YOUR_USERNAME/lfudacaching"
license: Apache-2.0
author: "Your Name"
maintainer: "your.email@example.com"
copyright: "2025"
synopsis: LFUDA cache
description: LFUDA (Least Frequently Used with Dynamic Aging) cache implementation in Haskell
category: Data
extra-source-files:
  - README.md

language: GHC2021

default-extensions:
- NoImplicitPrelude

ghc-options:
- -Weverything
- -Wno-prepositive-qualified-module
- -Wno-missing-safe-haskell-mode
- -Wno-missing-import-lists
- -Wno-unsafe
- -Wno-all-missed-specialisations
- -Wno-missed-specialisations
- -Werror=identities
- -Werror=missing-methods
- -Werror=incomplete-record-updates
- -Werror=incomplete-patterns
- -Werror=missing-fields
- -Werror=ambiguous-fields
- -Werror=incomplete-uni-patterns
- -Werror=partial-fields
- -Werror=redundant-constraints

dependencies:
  - base

library:
  source-dirs: src
  exposed-modules:
    - Data.LfudaCache
  dependencies:
    - deepseq
    - hashable
    - psqueues
    - ghc-prim

tests:
  lfuda-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - lfudacaching
      - tasty
      - tasty-hunit
    other-modules:
      - Test.Data.LfudaCache
